export const uiText = {
  en: {
    title: "Voice Buddy",
    subtitle: "Your intelligent voice assistant",
    listening: "Listening...",
    speakNow: "Speak now...",
    startPrompt: "Press start and begin speaking",
    responsePlaceholder: "Response will appear here",
    history: "History",
    noHistory: "No conversations yet",
    startHistory: "Start speaking to build your history",
    stopSpeaking: "Stop Speaking",
    speakAgain: "Speak Again",
    processing: "Processing your request...",
    noSpeech: "No speech detected. Please try again.",
  },
  hi: {
    title: "वॉइस बडी",
    subtitle: "आपका बुद्धिमान आवाज सहायक",
    listening: "सुन रहा हूँ...",
    speakNow: "अब बोलें...",
    startPrompt: "शुरू करें और बोलना शुरू करें",
    responsePlaceholder: "प्रतिक्रिया यहां दिखाई देगी",
    history: "इतिहास",
    noHistory: "अभी तक कोई वार्तालाप नहीं",
    startHistory: "अपना इतिहास बनाने के लिए बोलना शुरू करें",
    stopSpeaking: "बोलना बंद करें",
    speakAgain: "फिर से बोलें",
    processing: "आपका अनुरोध प्रसंस्करण...",
    noSpeech: "कोई आवाज नहीं मिली। कृपया पुनः प्रयास करें।",
  },
};
